--------------------------------------------------------------------------------------------------------------|>
--[+] Variables |~| Переменные :--:--:--:--:--:--:--:--:--:--:--:}>                                           |>
--------------------------------------------------------------------------------------------------------------|>
if not (jlib) then jlib = {} end
if not (jlib.cfg) then jlib.cfg = {} end
if not (jlib.cfg.lans) then jlib.cfg.lans = {} end

--------------------------------------------------------------------------------------------------------------|>
--[+] Languages |~| Языки :--:--:--:--:--:--:--:--:--:--:--:}>                                                |>
--------------------------------------------------------------------------------------------------------------|>
jlib.cfg.lans = {
	["en"] = {
		--[*] Basic actions |~| Основные действия |>
		["yes"] = "Yes",
		["no"] = "No",
		["ok"] = "OK",
		["cancel"] = "Cancel",
		["apply"] = "Apply",
		["save"] = "Save",
		["close"] = "Close",
		["back"] = "Back",
		["next"] = "Next",
		["confirm"] = "Confirm",
		["delete"] = "Delete",
		["edit"] = "Edit",
		["create"] = "Create",
		--[*] Additions |~| Дополнения |>
		["in"] = "in",
		["on"] = "on",
		["to"] = "to",
		["for"] = "for",
		["from"] = "from",
		["behind"] = "behind",
		["because"] = "because",
		--[*] UI elements |~| Элементы польз. интерфейса |>
		["name"] = "Name",
		["description"] = "Description",
		["title"] = "Title",
		["author"] = "Author",
		["version"] = "Version",
		["settings"] = "Settings",
		["options"] = "Options",
		["search"] = "Search",
		["filter"] = "Filter",
		["sort"] = "Sort",
		["refresh"] = "Refresh",
		["language"] = "Language",
		["change"] = "Change",
		--[*] Categories |~| Категории |>
		["general"] = "General",
		["appearance"] = "Appearance",
		["interface"] = "Interface",
		["sound"] = "Sound",
		["sound_ui"] = "Turn on sounds",
		["sound_ui_volume"] = "Volume of sounds",
		["controls"] = "Controls",
		["advanced"] = "Advanced",
		["main-menu"] = "Main menu",
		["text"] = "Text",
		--[*] States |~| Состояния |>
		["enabled"] = "Enabled",
		["disabled"] = "Disabled",
		["active"] = "Active",
		["inactive"] = "Inactive",
		["ready"] = "Ready",
		["on"] = "On",
		["off"] = "Off",
		["visible"] = "Visible",
		["hidden"] = "Hidden",
		["your-request"] = "Your request...",
		["not-selected"] = "not selected",
		--[*] Colors |~| Цвета |>
		["color"] = "Color",
		["theme"] = "Theme",
		["background"] = "Background",
		["foreground"] = "Foreground",
		["accent"] = "Accent Color",
		--[*] Sizes |~| Размеры |>
		["size"] = "Size",
		["small"] = "Small",
		["medium"] = "Medium",
		["large"] = "Large",
		["scale"] = "Scale",
		--[*] Notifications |~| Уведомления |>
		["success"] = "Success",
		["error"] = "Error",
		["warning"] = "Warning",
		["info"] = "Information",
		["loading"] = "Loading...",
		["processing"] = "Processing...",
		["oops"] = "Oops",
		--[*] Notifications (valid) |~| Уведомления (действительность) |>
		["accept-notify"] = "Are you sure you want to do this?",
		["no-access-to-data"] = "Access to the 'data' folder is closed! Saving the settings is not possible.",
		["oops-dont-selected"] = "Oops. You haven't chosen anything yet",
		["oops-nothing-specified"] = "nothing is specified",
		["oops-forbidden-symbol"] = "there is a forbidden symbol",
		["oops-should-be-minimum"] = "there should be a minimum",
		["oops-shouldnt-be-more"] = "there shouldn't be more",
		["oops-unavailable-value-entered"] = "an unavailable value has been entered",
		["oops-symbol"] = "symbol",
		["oops-symbols"] = "symbols",
		["tip-for-bind"] = "RMB - select a button  LMB - clear the field",	
		["jlib-download"] = "The library has been uploaded successfully",
		--[*] Time |~| Время |>
		["seconds"] = "seconds",
		["minutes"] = "minutes",
		["hours"] = "hours",
		["days"] = "days",
		--[*] Network |~| Сеть |>
		["connect"] = "Connect",
		["disconnect"] = "Disconnect",
		["server"] = "Server",
		["client"] = "Client",
		["ping"] = "Ping",
		["players"] = "Players",
		--[*] GMod specific |~| Свойственное для GMod |>
		["spawn"] = "Spawn",
		["tool"] = "Tool",
		["entity"] = "Entity",
		["npc"] = "NPC",
		["vehicle"] = "Vehicle",
		["weapon"] = "Weapon",
		["props"] = "Props",
		["dupe"] = "Duplication",
		["save_dupe"] = "Save Dupe",
		["load_dupe"] = "Load Dupe"
	},

	["de"] = {
		--[*] Basic actions |~| Основные действия |>
		["yes"] = "Ja",
		["no"] = "Nein",
		["ok"] = "OK",
		["cancel"] = "Abbrechen",
		["apply"] = "Übernehmen",
		["save"] = "Speichern",
		["close"] = "Schließen",
		["back"] = "Zurück",
		["next"] = "Weiter",
		["confirm"] = "Bestätigen",
		["delete"] = "Löschen",
		["edit"] = "Bearbeiten",
		["create"] = "Erstellen",
		--[*] Additions |~| Дополнения |>
		["in"] = "in",
		["on"] = "auf",
		["to"] = "zu",
		["for"] = "für",
		["from"] = "von",
		["behind"] = "hinter",
		["because"] = "weil",
		--[*] UI elements |~| Элементы польз. интерфейса |>
		["name"] = "Name",
		["description"] = "Beschreibung",
		["title"] = "Titel",
		["author"] = "Autor",
		["version"] = "Version",
		["settings"] = "Einstellungen",
		["options"] = "Optionen",
		["search"] = "Suchen",
		["filter"] = "Filter",
		["sort"] = "Sortieren",
		["refresh"] = "Aktualisieren",
		["language"] = "Sprache",
		["change"] = "Ändern",
		--[*] Categories |~| Категории |>
		["general"] = "Allgemein",
		["appearance"] = "Aussehen",
		["interface"] = "Oberfläche",
		["sound"] = "Sound",
		["sound_ui"] = "Sounds aktivieren",
		["sound_ui_volume"] = "Lautstärke der Töne",
		["controls"] = "Steuerung",
		["advanced"] = "Erweitert",
		["main-menu"] = "Hauptmenü",
		["text"] = "Text",
		--[*] States |~| Состояния |>
		["enabled"] = "Aktiviert",
		["disabled"] = "Deaktiviert",
		["active"] = "Aktiv",
		["inactive"] = "Inaktiv",
		["ready"] = "Bereit",
		["on"] = "Ein",
		["off"] = "Aus",
		["visible"] = "Sichtbar",
		["hidden"] = "Versteckt",
		["your-request"] = "Ihre Anfrage...",
		["not-selected"] = "nicht ausgewählt",
		--[*] Colors |~| Цвета |>
		["color"] = "Farbe",
		["theme"] = "Thema",
		["background"] = "Hintergrund",
		["foreground"] = "Vordergrund",
		["accent"] = "Akzentfarbe",
		--[*] Sizes |~| Размеры |>
		["size"] = "Größe",
		["small"] = "Klein",
		["medium"] = "Mittel",
		["large"] = "Groß",
		["scale"] = "Skalierung",
		--[*] Notifications |~| Уведомления |>
		["success"] = "Erfolg",
		["error"] = "Fehler",
		["warning"] = "Warnung",
		["info"] = "Information",
		["loading"] = "Lädt...",
		["processing"] = "Verarbeitung...",
		["oops"] = "Hoppla",
		--[*] Notifications (valid) |~| Уведомления (действительность) |>
		["accept-notify"] = "Sind Sie sicher, dass Sie dies tun möchten?",
		["no-access-to-data"] = "Zugriff auf den 'data'-Ordner ist geschlossen! Speichern der Einstellungen nicht möglich.",
		["oops-dont-selected"] = "Hoppla. Sie haben noch nichts ausgewählt",
		["oops-nothing-specified"] = "nichts angegeben",
		["oops-forbidden-symbol"] = "es gibt ein verbotenes Symbol",
		["oops-should-be-minimum"] = "es sollte mindestens sein",
		["oops-shouldnt-be-more"] = "es sollte nicht mehr sein",
		["oops-unavailable-value-entered"] = "ein nicht verfügbarer Wert wurde eingegeben",
		["oops-symbol"] = "Symbol",
		["oops-symbols"] = "Symbole",
		["tip-for-bind"] = "RMB - Wählen Sie die Schaltfläche aus  LMB - das Feld löschen",	
		["jlib-download"] = "Die Bibliothek wurde erfolgreich geladen",
		--[*] Time |~| Время |>
		["seconds"] = "Sekunden",
		["minutes"] = "Minuten",
		["hours"] = "Stunden",
		["days"] = "Tage",
		--[*] Network |~| Сеть |>
		["connect"] = "Verbinden",
		["disconnect"] = "Trennen",
		["server"] = "Server",
		["client"] = "Client",
		["ping"] = "Ping",
		["players"] = "Spieler",
		--[*] GMod specific |~| Свойственное для GMod |>
		["spawn"] = "Erstellen",
		["tool"] = "Werkzeug",
		["entity"] = "Entität",
		["npc"] = "NPC",
		["vehicle"] = "Fahrzeug",
		["weapon"] = "Waffe",
		["props"] = "Props",
		["dupe"] = "Duplikat",
		["save_dupe"] = "Duplikat speichern",
		["load_dupe"] = "Duplikat laden"
	},	

	["ru"] = {
		--[*] Basic actions |~| Основные действия |>
		["yes"] = "Да",
		["no"] = "Нет",
		["ok"] = "ОК",
		["cancel"] = "Отмена",
		["apply"] = "Применить",
		["save"] = "Сохранить",
		["close"] = "Закрыть",
		["back"] = "Назад",
		["next"] = "Далее",
		["confirm"] = "Подтвердить",
		["delete"] = "Удалить",
		["edit"] = "Редактировать",
		["create"] = "Создать",
		--[*] Additions |~| Дополнения |>
		["in"] = "в",
		["on"] = "на",
		["to"] = "к",
		["for"] = "для",
		["from"] = "от",
		["behind"] = "за",
		["because"] = "из-за",
		--[*] UI elements |~| Элементы польз. интерфейса |>
		["name"] = "Название",
		["description"] = "Описание",
		["title"] = "Заголовок",
		["author"] = "Автор",
		["version"] = "Версия",
		["settings"] = "Настройки",
		["options"] = "Опции",
		["search"] = "Поиск",
		["filter"] = "Фильтр",
		["sort"] = "Сортировка",
		["refresh"] = "Обновить",
		["language"] = "Язык",
		["change"] = "Изменить",
		--[*] Categories |~| Категории |>
		["general"] = "Основные",
		["appearance"] = "Внешний вид",
		["interface"] = "Интерфейс",
		["sound"] = "Звук",
		["sound_ui"] = "Включить звуки",
		["sound_ui_volume"] = "Громкость звуков",
		["controls"] = "Управление",
		["advanced"] = "Дополнительно",
		["main-menu"] = "Главное меню",
		["text"] = "Текст",
		--[*] States |~| Состояния |>
		["enabled"] = "Включено",
		["disabled"] = "Выключено",
		["active"] = "Активно",
		["inactive"] = "Неактивно",
		["ready"] = "Готово",
		["on"] = "Вкл",
		["off"] = "Выкл",
		["visible"] = "Видимо",
		["hidden"] = "Скрыто",
		["your-request"] = "Ваш запрос...",
		["not-selected"] = "не выбрано",
		--[*] Colors |~| Цвета |>
		["color"] = "Цвет",
		["theme"] = "Тема",
		["background"] = "Фон",
		["foreground"] = "Передний план",
		["accent"] = "Акцентный цвет",
		--[*] Sizes |~| Размеры |>
		["size"] = "Размер",
		["small"] = "Маленький",
		["medium"] = "Средний",
		["large"] = "Большой",
		["scale"] = "Масштаб",
		--[*] Notifications |~| Уведомления |>
		["success"] = "Успех",
		["error"] = "Ошибка",
		["warning"] = "Предупреждение",
		["info"] = "Информация",
		["loading"] = "Загрузка...",
		["processing"] = "Обработка...",
		["oops"] = "Упс",
		--[*] Notifications (valid) |~| Уведомления (действительность) |>
		["accept-notify"] = "Вы точно хотите совершить это действие?",
		["no-access-to-data"] = "Доступ к папке 'data' закрыт! Сохранение настроек невозможно.",
		["oops-dont-selected"] = "Упс. Вы еще ничего не выбрали",
		["oops-nothing-specified"] = "ничего не указано",
		["oops-forbidden-symbol"] = "есть запрещённый символ",
		["oops-should-be-minimum"] = "должно быть минимум",
		["oops-shouldnt-be-more"] = "не должно быть больше",
		["oops-unavailable-value-entered"] = "введено недоступное значение",
		["oops-symbol"] = "символа",
		["oops-symbols"] = "символов",
		["tip-for-bind"] = "ПКМ - выбрать кнопку  ЛКМ - очистить поле",
		["jlib-download"] = "Библиотека успешно загружена",
		--[*] Time |~| Время |>
		["seconds"] = "секунд",
		["minutes"] = "минут",
		["hours"] = "часов",
		["days"] = "дней",
		--[*] Network |~| Сеть |>
		["connect"] = "Подключиться",
		["disconnect"] = "Отключиться",
		["server"] = "Сервер",
		["client"] = "Клиент",
		["ping"] = "Пинг",
		["players"] = "Игроки",
		--[*] GMod specific |~| Свойственное для GMod |>
		["spawn"] = "Создать",
		["tool"] = "Инструмент",
		["entity"] = "Энтити",
		["npc"] = "NPC",
		["vehicle"] = "Транспорт",
		["weapon"] = "Оружие",
		["props"] = "Пропы",
		["dupe"] = "Дубликат",
		["save_dupe"] = "Сохранить дубликат",
		["load_dupe"] = "Загрузить дубликат"
	}
}

-->                      						 _M_                                      
-- [*] Who are you, Warrior? |~| Кто ты, Воин?  (0-0)                   
-->                                              -w-  